# Complete list of all available properties: https://docs.platform.sh/create-apps/app-reference.html

# A unique name for the app. Must be lowercase alphanumeric characters. Changing the name destroys data associated
# with the app.
name: admin

# The runtime the application uses.
# Complete list of available runtimes: https://docs.platform.sh/create-apps/app-reference.html#types
type: nodejs:16

# Resources and CPU to allocate to the service
# Complete list of available sizes: https://docs.platform.sh/create-apps/app-reference.html#sizes
size: L

# Fine-tune allocated resources
# https://docs.platform.sh/create-apps/flexible-resources.html#performance-profiles
resources:
  base_memory: 1024
  memory_ratio: 1024

# The size of the persistent disk of the application (in MB). Minimum value is 128.
disk: 1024

# Mounts define directories that are writable after the build is complete. If set as a local source, disk property is required.
# More information: https://docs.platform.sh/create-apps/app-reference.html#mounts
mounts:
  '/.tmp_platformsh': 'shared:files/tmp_platformsh'
  '/build': 'shared:files/build'
  '/.cache': 'shared:files/.cache'
  '/node_modules/.cache': 'shared:files/node_modules/.cache'

# The web key configures the web server running in front of your app.
# More information: https://docs.platform.sh/create-apps/app-reference.html#web
web:
  locations:
    "/admin":
      # The public directory of the app, relative to its root.
      root: "build"
      # The front-controller script to send non-static requests to.
      passthru: "/admin/index.html"
      # Default script that handle request
      index:
        - "index.html"
      # The number of seconds whitelisted (static) content should be cached.
      expires: 300s
      scripts: true
      allow: true
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
          allow: true
        ^/admin/robots\.txt$:
          allow: true
        ^/admin/manifest\.json$:
          allow: true
        ^/admin/_next:
          allow: true
        ^/admin/sitemap:
          allow: true
      headers:
        Access-Control-Allow-Origin: "*"

# Define variables used by this app (env, runtime settings, ...)
# https://docs.platform.sh/create-apps/app-reference.html#variables
variables:
  env:
    NODE_OPTIONS: '--max-old-space-size=1536'

# Specifies a default set of build tasks to run. Flavors are language-specific.
# More information: https://docs.platform.sh/create-apps/app-reference.html#build
build:
  flavor: none

# Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
# More information: https://docs.platform.sh/create-apps/app-reference.html#hooks
hooks:
  # The build hook is run after any build flavor.
  # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#build-hook
  build: |
    set -eu
    corepack yarn install --immutable --force
  # The post_deploy hook is run after the app container has been started and after it has started accepting requests.
  # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#deploy-hook
  post_deploy: |
    corepack yarn run build
